//! Raw FFI bindings to the CTM C++ engine, generated by bindgen from `cpp/include/ctm_ffi.h`.
//! Use the `ctm-engine` crate for the safe wrapper.

#![allow(
    non_camel_case_types,
    non_snake_case,
    non_upper_case_globals,
    dead_code,
    clippy::all
)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
